In [11]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [12]:
%%time

start_time = time.time()
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time-start_time
print (f"{elapsed_time : .10f}")

 0.0000000000
CPU times: total: 0 ns
Wall time: 0 ns


In [16]:
# torch.stack, torch.multinomial, torch.tril, torch.triu, input.T/input.transpose, nn.linear, torch.concat, F.softmax (show all methods/functions with pytorch docs

#define a probability tensor
probabilities = torch.tensor([0.1, 0.9]) #means 10% chance we get a 0, 90% chance we get a 1
samples = torch.multinomial(probabilities, num_samples = 10, replacement = True)
print(samples)



tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [17]:
tensor = torch.tensor([1,2,3,4])

out = torch.cat((tensor, torch.tensor([5])), dim=0) #creates a tensor that contains 5 and concats both tensors

out

tensor([1, 2, 3, 4, 5])

In [22]:
out = torch.tril(torch.ones(5,5)) #tril means trianlge lower

out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [23]:
out = torch.triu(torch.ones(5,5)) # triu means triangle upper

out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [41]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) ==0, float('-inf') ) #creates triangle upper with float
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [38]:
torch.exp(out) # carries out exponential on the above tensor values. it raises 2.71 (a constant in .exp function) and raises it to the power of the value in the tensor. e.g. 2.71 ^ 0


tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [47]:
input = torch.zeros(2,3, 4)
out = input.transpose(0,2) # positions of values in tensor being flipped
out.shape

torch.Size([4, 3, 2])

In [49]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

#stack the tensor along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor
                        

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [55]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3,3, bias = False) #means linear transformation
print(linear(sample))

tensor([ 0.3044, -3.9561, -3.3308], grad_fn=<SqueezeBackward4>)


In [62]:
import torch.nn.functional as F
#create a tensor

tensor = torch.tensor([1.0, 2.0, 3.0])

#apply softmax

softmax_output = F.softmax(tensor, dim=0)
softmax_output

tensor([0.0900, 0.2447, 0.6652])

In [63]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()
rand = (torch_rand1 @ torch_rand2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .8f}")

start_time = time.time()
rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()
elapsed_time = end_time - start_time

print(f"{elapsed_time: .8f}")



 0.25505710
 0.34729242


C:\Users\Littl\AppData\Local\Temp\ipykernel_13280\2302436052.py:14: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(np_rand1, np_rand2)


In [10]:
import torch
print("PyTorch sees GPU:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))
    print("CUDA version:", torch.version.cuda)

PyTorch sees GPU: False
